In [ ]:
# 데이터: You say goodbye and I say hello.

# 3-3-1. 맥락과 타깃
 - word2vec에서 이용하는 신경망의 입력: 맥락(context)
 - 맥락의 정답 레이블: 맥락에 둘러싸인 단어(= target)
 - 신경망에 맥락을 입력했을 때 타깃이 출현할 확률을 높이는 것이 목표. 

#### 문장 데이터로부터 맥락과 타깃 구분하기
 - 데이터: You say goodbye and I say hello. 
 
 - 타깃 say : 맥락 you, goodbye
 - 타깃 goodbye : 맥락 say, and
 - 타깃 and : 맥락 goodbye, I
 - 타깃 I : 맥락 and, say
 - 타깃 say : 맥락 I, hello
 - 타깃 hello: 맥락 say, .

In [6]:
#코퍼스에서 맥락과 타깃을 만드는 함수를 구현하기 전에, 코퍼스 텍스트를 먼저 단어 ID로 변환해야 한다.
import sys
sys.path.append('..')
from common.util import preprocess

text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
print(corpus)

print(id_to_word)

[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


In [29]:
#맥락, 타깃을 만드는 함수 구현.
#corpus를 주면 맥락과 타깃을 반환함.
def create_contexts_target(corpus, window_size = 1):
    target = corpus[window_size : -window_size]  #corpus[1:-1]
    contexts = []
    
    for idx in range(window_size, len(corpus) - window_size):  #(1, len(corpus) - 1)
        cs = []
        for t in range(-window_size, window_size + 1): #range(-1, 2)
            if t == 0:
                continue
            cs.append(corpus[idx + t])   #index를 이용하여 append하기 때문에 list가 담기지 않고 원소 자체가 담기는 것이다.
                                         #그래서 [[0, 2]] 식으로 나오는 것이다.
            #print(cs)
        contexts.append(cs)
        #print(contexts)
        
    return np.array(contexts), np.array(target)

In [31]:
contexts, target = create_contexts_target(corpus, window_size = 1)
print(contexts)
print(target)                             

[[0 2]
 [1 3]
 [2 4]
 [3 1]
 [4 5]
 [1 6]]
[1 2 3 4 1 5]


# 3-3-2. one-hot-encoding으로 변환

  - 맥락과 타깃을 one-hot-encoding 변환해야 한다.
  - conver_one_hot() 함수 사용

In [32]:
#아래 코드로 학습 데이터 준비 완료!
import sys
sys.path.append('..')
from common.util import preprocess, create_contexts_target, convert_one_hot
                                                            #convert_one_hot(단어 ID 목록, 어휘 수)

text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)

contexts, target = create_contexts_target(corpus, window_size = 1)

vocab_size = len(word_to_id)
target = convert_one_hot(target, vocab_size)
contexts = convert_one_hot(contexts, vocab_size)